databases:
  - name: proyecto
    plan: free
    databaseName: proyecto
    user: proyecto

services:
  - type: web
    name: proyecto
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn proyecto.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proyecto
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4